Repository androidvitb/Nova-Bank, pull requests merged in 2025-02, with the labels that each got.

#14 added scroll to top button
  src/pages/Homepage.js
Labels: acwoc, medium

#16 Implemented OTP Verification at the time of registration
  .env.example
  .gitignore
  models/OTP.js
  package.json
  src/app/api/register/route.js
  src/components/Footer.js
  src/pages/RegisterPage.js
  utils/emailService.js
Labels: acwoc, hard

#18 Added Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/general_issue.md
Labels: acwoc, medium

#19 Enhanced text visibility in footer
  src/components/Footer.js
Labels: acwoc, easy

#20 Added the Favicon to the Nova Bank website
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  src/app/layout.js
Labels: acwoc, easy

#23 Password Reset and Authentication Enhancement
  .env.example
  models/User.js
  package.json
  src/app/api/forgot-password/route.js
  src/app/api/reset-password/route.js
  src/app/reset-password/page.js
  src/pages/LoginPage.js
  src/pages/ResetPasswordPage.js
  utils/emailService.js
Labels: acwoc, hard

#25 Add Live Chatbot Feature Integration Using react-chatbot-kit
  .env.example
  package-lock.json
  package.json
  src/app/globals.css
  src/app/page.js
  src/components/Chatbot/FloatingChatButton.js
  src/components/Homepage/ActionProvider.js
  src/components/Homepage/Chatbot.js
  src/components/Homepage/FeatureSection.js
  src/components/Homepage/HeroSection.js
  src/components/Homepage/MessageParser.js
  src/components/Homepage/config.js
Labels: acwoc, hard

#27 fixed overlapping of chatbot and scroll button
  package-lock.json
  src/components/Chatbot/FloatingChatButton.js
  src/components/Homepage/Chatbot.js
Labels: acwoc, easy

#29 Add Dashboard UI with Paper Money, Transfer, Deposit & Expense Chart
  .env.example
  context/account.js
  context/authContext.js
  models/Account.js
  models/Transaction.js
  package-lock.json
  package.json
  src/app/_app.js
  src/app/api/register/route.js
  src/components/BankDashboard.js
  src/components/Homepage/config.js
  src/components/Navbar.js
  src/pages/RegisterPage.js
  src/pages/_app.js
  src/pages/api/accounts/getBalance.js
  src/pages/api/accounts/myaccount.js
  src/pages/api/transactions/index.js
  src/pages/api/transactions/recent.js
  src/pages/dashboard.js
  src/pages/dashboard/deposit.js
  src/pages/dashboard/transfer.js
  src/pages/dashboard/withdraw.js
  src/pages/open-account.js
  utils/dbConnect.js
Labels: acwoc, hard

#31 [UI Enhancement] Advanced Animations and Interactive Components for Homepage
  src/components/Homepage/FeatureSection.js
  src/components/Homepage/HeroSection.js
  src/components/Homepage/SolutionSection.js
  src/components/Homepage/StatsSection.js
Labels: acwoc, hard
